<html>
    <head>
        <title>Home</title>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({
                google_ad_client: "ca-pub-8248356676694292",
                enable_page_level_ads: true
            });
        </script>
    </head>
    <body>
        <h1>Thanks For visiting!!</h1>
    </body>
</html>
